version = 0.1
[default.deploy.parameters]
stack_name = "prod-todolistAWS4"
s3_bucket = "todo-sam-prod-angelabtte-2025"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=todo-prod-table"
